# guide used to convert sqlite3 to postgresql:
# https://medium.com/@rachid1982fsb/sqlite3-to-postgresql-on-rails-app-df825e96ca1a

development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: james
  password:
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: james
  password:
  timeout: 5000